### PR TITLE
Add methods to save and remove track/albums

### PR DESCRIPTION
**Pull request by andodet**
Hi @charlie86, really liked the project and implemented couple methods I've found in the Projects pane.

Feel free to comment where needed or to suggest changes.

### CODE REVIEW

**Comment by antaldaniel** [comment]
@womeimingzi11, @andodet, your PR's are great but conflicing. I took over the daily maintainance issues. We have a new release on CRAN, and I am going through now all remaining PRs.  Stay tuned, I'll try to figure out how to make both PRs work (and credited.)

**Comment by andodet** [comment]
@antaldaniel Thanks for your time on this. Also, feel free to pick @womeimingzi11's PR if it makes more sense.

**Comment by womeimingzi11** [comment]
> @antaldaniel Thanks for your time on this. Also, feel free to pick @womeimingzi11's PR if it makes more sense.

Really sorry for the conflict PR that I made. I found @andodet pulled this request earlier. It may be more reasonable to merge this PR. 

Appreciate for this confusion made by me.

**Comment by antaldaniel** [comment]
@andodet @womeimingzi11 I'll review both PR's and subsequent changes I made to get the package back to CRAN, work them into one (with slight modifications) and attribute both of you as contributors to this.  It'll be sometime next wee I guess, I will close the PR requests when done.  Thanks for both for taking the initiative, and let me know if the current 2.2.2 has any issues. (I already fixed a very minor bug compared to the new CRAN release.)

**Pull request closed without merging**
