### PR TITLE
Add create_playlist, add_to_playlist functions and get_album_meta

### PR DESCRIPTION
**Pull request by Phippsy**
Hi - believe these functions should work, cheers!

Example below:

```r
# Find my favourite tracks ------------------------------------------------
top_tracks <- get_my_top_tracks(time_range = 'long_term') 

# Append the track features
top_track_features <- get_track_audio_features(tracks = top_tracks) %>% 
  left_join(top_tracks, by = "track_uri")

# Arrange tracks in order of energy, then danceability
top_tracks_sequence <- top_track_features %>% 
  mutate(energy_cat = cut(energy, breaks = 6)) %>% 
  arrange(energy_cat, danceability) %>% 
  select(track_name, artist_name, album_name, energy_cat, danceability, track_uri)

# Create a new playlist, then add my top tracks, in order
hello_fromr <- create_playlist(username = 'rstats', playlist_name =  'hello from spotifyr!')
my_added_tracks <- add_to_playlist(username = 'rstats', playlist_id = hello_fromr$id, tracks =  top_tracks_sequence$track_uri)
```

### CODE REVIEW

**Comment by Phippsy** [comment]
Hi - added an extra function - `get_album_meta()` which provides album metadata. Hopefully this helps with issues relating to copyright and genre requests for albums. Cheers. 
#45 #44

**Comment by charlie86** [comment]
@Phippsy Awesome! I'm on vacation this week, but I'll take a look and likely merge next week. Thanks a bunch!

**Comment by Phippsy** [comment]
Appreciate the reply - happy hols!

**Comment by donal** [comment]
Just to let you know, I'm @donal and it was @Phippsy who made these commits. @Phippsy, you might want to take a look at [Why are my commits linked to the wrong user?](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/) (and [reach out to GitHub support](https://github.com/contact) if you have any questions about this). :v:

**Comment by Phippsy** [comment]
Thanks @donal - I think this is just down to @charlie86 tagging you [above](https://github.com/charlie86/spotifyr/pull/46#commitcomment-30021497), though, right? 
My bad for having a weird username

**Comment by donal** [comment]
> I think this is just down to @charlie86 tagging you above, though, right?

Correct!

> My bad for having a weird username

You're not the only one 😄

**Comment by Phippsy** [comment]
P.S. @charlie86 , I named the function `get_album_meta()` only because you had a previous function `get_album()` so I wanted to avoid conflict.
IMO it makes sense to rename `get_album_meta()` --> `get_albums()`, since this more closely matches the [API request name](https://developer.spotify.com/documentation/web-api/reference/albums/get-several-albums/) but I wanted to leave that choice to you. Cheers.

**Comment by charlie86** [comment]
@Phippsy Fantastic job! Really appreciate your work here. 

I agree that `get_album_meta()` should be named `get_albums()`. For context, the original `get_albums()` was deprecated and renamed `get_artist_albums()` because it was searching for albums by artist (so `get_albums()` was just a poor original naming choice). Your function is more true to the API's `albums` endpoint.

I'll go ahead and merge and update the name. Thanks again!

**Comment by charlie86** [comment]
@donal Sorry about that! My bad for trying to answer github issues on my phone

**Comment by Phippsy** [comment]
Brilliant - thanks and delighted to make a contribution. As an R user and music lover, I had tons of fun with your package - cheers for putting it together.

**Comment by charlie86** [comment]
@Phippsy thanks, glad you enjoy it! To cite your contributions in the author list, what email would you prefer?

**Comment by Phippsy** [comment]
donal.phipps@gmail.com is great, thank you.

**Pull request merged**
